name: Generate Podcast Feeds
on: [push] 
jobs: 
  build: 
    runs-on: ubuntu-lates
    steps:
      - name: Chekout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: Alexeygrb/podcast-generator@main
         
